# Default values for mgit
# This is a YAML-formatted file.

# Image configuration
image:
  repository: ghcr.io/steveant/mgit
  pullPolicy: IfNotPresent
  tag: ""  # Overrides the image tag whose default is the chart appVersion

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Deployment configuration
replicaCount: 1

# Service account configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod annotations and labels
podAnnotations: {}
podLabels: {}

# Security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 8080

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: mgit.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: mgit-tls
  #    hosts:
  #      - mgit.local

# Resource limits and requests
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Horizontal Pod Autoscaler
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Pod Disruption Budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1
  # maxUnavailable: 1

# Node selection
nodeSelector: {}
tolerations: []
affinity: {}

# Environment configuration
env:
  # mgit-specific environment variables
  MGIT_CONFIG_DIR: "/home/mgit/.mgit"
  MGIT_DATA_DIR: "/app/data"
  MGIT_LOG_LEVEL: "INFO"
  MGIT_DEFAULT_CONCURRENCY: "5"
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"

# Environment variables from secrets/configmaps
envFrom: []
  # - secretRef:
  #     name: mgit-secrets
  # - configMapRef:
  #     name: mgit-config

# Persistent storage
persistence:
  config:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 1Gi
    annotations: {}
  data:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 10Gi
    annotations: {}

# Health checks
livenessProbe:
  enabled: true
  exec:
    command:
      - /usr/local/bin/healthcheck.sh
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  exec:
    command:
      - /usr/local/bin/healthcheck.sh
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Startup probe
startupProbe:
  enabled: true
  exec:
    command:
      - /usr/local/bin/healthcheck.sh
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30

# Command and args
command: []
args: []

# Init containers
initContainers: []

# Sidecar containers
sidecars: []

# Volume mounts
volumeMounts:
  - name: config
    mountPath: /home/mgit/.mgit
  - name: data
    mountPath: /app/data
  - name: tmp
    mountPath: /tmp

# Additional volumes
volumes:
  - name: tmp
    emptyDir: {}

# Network policy
networkPolicy:
  enabled: false
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []

# Service monitor for Prometheus
serviceMonitor:
  enabled: false
  namespace: ""
  labels: {}
  interval: 30s
  scrapeTimeout: 10s
  path: /metrics

# Pod monitor for Prometheus
podMonitor:
  enabled: false
  namespace: ""
  labels: {}
  interval: 30s
  scrapeTimeout: 10s
  path: /metrics

# Metrics configuration
metrics:
  enabled: false
  service:
    type: ClusterIP
    port: 9090

# Configuration files
configFiles: {}
  # config.yaml: |
  #   key: value

# Secret files
secretFiles: {}
  # secret.yaml: |
  #   key: value

# External secrets
externalSecrets:
  enabled: false
  secretStore:
    name: ""
    kind: SecretStore
  target:
    name: mgit-secrets
    creationPolicy: Owner
  data: []
    # - secretKey: azure-devops-pat
    #   remoteRef:
    #     key: mgit/azure-devops-pat

# Tests
tests:
  enabled: true
  image:
    repository: ghcr.io/steveant/mgit
    tag: ""
    pullPolicy: IfNotPresent