# Docker Compose override for local development
# This file provides development-friendly defaults and can be customized locally
version: '3.8'

services:
  mgit:
    # Development overrides for the main service
    environment:
      # More verbose logging for development
      - MGIT_LOG_LEVEL=DEBUG
    
    # Mount local directories for easier development
    volumes:
      # Mount current directory for live code changes (development only)
      - .:/app/src:ro
      # Local configuration directory
      - ./docker/config:/home/mgit/.mgit
      # Local data directory
      - ./docker/data:/app/data
    
    # Remove read-only filesystem for development
    read_only: false
    
    # Remove security restrictions for easier debugging
    security_opt: []
    
    # Interactive mode for development
    stdin_open: true
    tty: true

  mgit-dev:
    # Additional development tools and configurations
    environment:
      # Development environment variables
      - MGIT_DEV_MODE=true
      - MGIT_DEBUG=true
      - PYTHONDEBUG=1
    
    # Additional volume mounts for development
    volumes:
      # Mount additional development tools
      - ./tests:/app/tests
      - ./docs:/app/docs
      - ./scripts:/app/scripts
    
    # Port mapping for any development services (if needed)
    # ports:
    #   - "8000:8000"  # Example port mapping