name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'mgit/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/ci.yml'
      - '.github/workflows/continuous-integration.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'mgit/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/ci.yml'
      - '.github/workflows/continuous-integration.yml'

jobs:
  # Call the shared CI workflow
  ci:
    name: Run CI
    uses: ./.github/workflows/ci.yml
    secrets: inherit