name: Release Automation

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v0.2.4)'
        required: true
        type: string
      release_type:
        description: 'Type of release'
        required: true
        type: choice
        options:
          - 'feature'
          - 'performance'
          - 'bugfix'
          - 'security'
          - 'maintenance'
        default: 'feature'
      pre_release:
        description: 'Mark as pre-release'
        required: false
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "Version: ${{ github.event.inputs.version }}"
          echo "Type: ${{ github.event.inputs.release_type }}"
          echo "Pre-release: ${{ github.event.inputs.pre_release }}"